packages:
  - packages/*
  - tools/*

catalog:
  "@lucide/vue": ^1.8.0
  "@types/node": ^25.6.0
  "@vitejs/plugin-vue": ^6.0.6
  bumpp: ^11.0.1
  overlayscrollbars: ^2.15.1
  playwright: ^1.59.1
  releaselog: ^7.0.2
  shiki: ^4.0.2
  simple-icons: ^16.16.0
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.18
  vite-plus: ^0.1.18
  vue: ^3.5.32
  vue-tsc: ^3.2.6

catalogMode: prefer
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
