packages:
  - packages/*
  - tools/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  "@lucide/vue": ^1.12.0
  "@types/node": ^25.6.0
  "@types/stats.js": ^0.17.4
  "@vitejs/plugin-vue": ^6.0.6
  "@vue-macros/define-render": ^3.1.2
  "@vue/compiler-dom": ^3.5.33
  "@vue/compiler-sfc": ^3.5.33
  bumpp: ^11.0.1
  overlayscrollbars: ^2.15.1
  playwright: ^1.59.1
  releaselog: ^8.0.0
  shiki: ^4.0.2
  simple-icons: ^16.18.0
  stats.js: ^0.17.0
  typescript: ^6.0.3
  unplugin-vue: ^7.2.0
  vite: ^8.0.11
  vite-plus: ^0.1.20
  void: 0.9.3
  vue: ^3.5.33
  vue-tsc: ^3.2.7

catalogMode: prefer
