packages:
  - packages/*
  - tools/*

catalog:
  "@chenglou/pretext": ^0.0.3
  "@lucide/vue": ^1.7.0
  "@types/node": ^24
  "@vitejs/plugin-vue": ^6.0.5
  bumpp: ^11.0.1
  overlayscrollbars: ^2.15.1
  playwright: ^1.58.2
  releaselog: ^7.0.2
  semver: ^7.7.4
  shiki: ^4.0.2
  simple-icons: ^16.14.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.17
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.31
  vue-tsc: ^3.2.6

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
